### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: /gpfs/scratch/bsc31/bsc31429/LiTS_database/train_files/liver_3_liver_minotaure/networks; No such file or directory

### ISSUE THREAD

**Issue by ParvatYadav** [imatge-upc/liverseg-2017-nipsws#20]
I am getting this error while running file seg_liver_train.py

Traceback (most recent call last):
  File "/content/liverseg-2017-nipsws/seg_liver_train.py", line 52, in <module>
    batch_size=batch_size, resume_training=False)
  File "/content/liverseg-2017-nipsws/seg_liver.py", line 575, in train_seg
    resume_training, config, finetune=0)
  File "/content/liverseg-2017-nipsws/seg_liver.py", line 484, in _train
    last_ckpt_path = tf.train.latest_checkpoint(logs_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/checkpoint_management.py", line 343, in latest_checkpoint
    if file_io.get_matching_files(v2_path) or file_io.get_matching_files(
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 361, in get_matching_files
    return get_matching_files_v2(filename)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 391, in get_matching_files_v2
    compat.as_bytes(single_filename), status)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /gpfs/scratch/bsc31/bsc31429/LiTS_database/train_files/liver_3_liver_minotaure/networks; No such file or directory

**Comment by miriambellver** [comment]
You should modify the paths and add yours in order to make it work! Thanks for the interest!
